# Server Configuration
server.port=${PORT:8080}

# Database Configuration (Handled by DatabaseConfig.java)
DATABASE_URL=${DATABASE_URL}
DATABASE_USERNAME=${DATABASE_USERNAME}
DATABASE_PASSWORD=${DATABASE_PASSWORD}

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# LinkedIn Configurations
linkedin.client.id=${LINKEDIN_CLIENT_ID}
linkedin.client.secret=${LINKEDIN_CLIENT_SECRET}
linkedin.redirect.uri=${LINKEDIN_REDIRECT_URI}
